name: ${NAME}
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - ${FRONTEND_PORT}:5173
    environment:
      - PUBLIC_API_URL=http://127.0.0.1:${BACKEND_PORT}
      - PUBLIC_WEBSOCKET_URL=ws://127.0.0.1:${BACKEND_PORT}
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${BACKEND_PORT}:3000
    environment:
      - RUST_LOG=info
      - NODE_PORT=${NODE_PORT}
      - PEER_ADDRESSES=${PEER_ADDRESSES}
