version: "3.8"
services:
  redis:
    image: redis@sha256:0c6f34a2d41992ee1e02d52d712c12ac46c4d5a63efdab74915141a52c529586
    entrypoint: ["redis-server", "--port", "${REDIS_PORT}"]
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5

  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    healthcheck:
      test:
        [
          "CMD",
          "cast",
          "chain-id",
          "--rpc-url",
          "http://localhost:8545",
        ]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "8545:8545"
    entrypoint: ["anvil", "--host", "0.0.0.0"]
    platform: linux/amd64
